### ISSUE TITLE
Unable to load stackstorm

### ISSUE THREAD

**Issue by lvdongbing** [StackStorm/hubot-stackstorm#119]
When starting st2chatops, it fails with following errors:
ERROR Unable to load /opt/stackstorm/chatops/node_modules/hubot-stackstorm/scripts/stackstorm: TypeError: Object prototype may only be an Object or null
  at Function.create (native)
  at module.exports (/opt/stackstorm/chatops/node_modules/st2client/index.js:122:17)
  at module.exports (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/scripts/stackstorm.js:114:13)
  at Robot.loadFile (/opt/stackstorm/chatops/node_modules/hubot/src/robot.coffee:358:11, <js>:226:13)
  at /opt/stackstorm/chatops/node_modules/hubot-stackstorm/index.js:38:13
  at Array.forEach (native)
  at module.exports (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/index.js:33:13)
  at Robot.loadExternalScripts (/opt/stackstorm/chatops/node_modules/hubot/src/robot.coffee:401:11, <js>:272:39)
  at /opt/stackstorm/chatops/node_modules/hubot/bin/hubot:119:11, <js>:126:26
  at fs.js:268:14
  at Object.oncomplete (fs.js:107:15)

**Comment by LindsayHill** [comment]
Could you provide a bit more info about your environment? OS, versions of `st2`, `st2chatops`

How did you configure this system? Did you use the scripted installation, or manual package install?

**Comment by lvdongbing** [comment]
OK. My OS is Ubuntu1404, st2 is1.5.0 and st2chatops is 1.5.0-2. I configured the system via manual package installing.

**Comment by armab** [comment]
@lvdongbing What's your `node.js` version?
```
node -v
```

**Comment by lvdongbing** [comment]
@armab v0.10.25

**Comment by LindsayHill** [comment]
See the "Setup ChatOps" section of the Installation docs https://docs.stackstorm.com/install/deb.html#id14

You should have done this as part of your setup:
```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```
That should give you a result like this:
```
lhill@st2chatops:~$ node -v
v4.4.7
```

**Comment by lvdongbing** [comment]
@LindsayHill Oh, that works for me, thank you!

**Comment by LindsayHill** [comment]
Good to hear it's working

**Comment by armab** [comment]
cc @Kami, you asked before what error it was with node `0.10` in https://github.com/StackStorm/hubot-stackstorm/pull/117#issuecomment-228108217
